from .db import get_connection

conn = get_connection()
c = conn.cursor()

c.execute(
    """
    CREATE TABLE IF NOT EXISTS Users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL
    )
    """
)

c.execute(
    """
    CREATE TABLE IF NOT EXISTS Subjects(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        priority INTEGER NOT NULL
    )
    """
)

c.execute(
    """
    CREATE TABLE IF NOT EXISTS Chapters(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        subject_id INTEGER NOT NULL,
        FOREIGN KEY(subject_id) REFERENCES Subjects(id)
    )
    """
)

c.execute(
    """
    CREATE TABLE IF NOT EXISTS Topics(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        chapter_id INTEGER NOT NULL,
        currently_studying BOOLEAN NOT NULL,
        completed BOOLEAN NOT NULL,
        priority INTEGER NOT NULL,
        FOREIGN KEY(chapter_id) REFERENCES Chapters(id)
    )
    """
)

c.execute(
    """
    CREATE TABLE IF NOT EXISTS Days(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL
    )
    """
)

c.execute(
    """
    CREATE TABLE IF NOT EXISTS Times (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        from_hour INTEGER NOT NULL,
        from_minute INTEGER NOT NULL,
        day_id INTEGER NOT NULL,
        FOREIGN KEY(day_id) REFERENCES Days(id)
    )
    """
)

conn.commit()
conn.close()